ci lint 3.0

diff --git a/.github/workflows/ci-pr-to-develop.yml b/.github/workflows/ci-pr-to-develop.yml
--- a/.github/workflows/ci-pr-to-develop.yml
+++ b/.github/workflows/ci-pr-to-develop.yml
@@ -2,16 +2,17 @@ name: PR (develop)
 
 on:
   pull_request:
-    branches: ['develop']
+    branches:
+      - develop
 
 jobs:
   run-lint:
     name: Run ESLint
-    runs-on: ubuntu-latest
+    runs-on: 'ubuntu-latest'
 
     steps:
       - name: Checkout repository
-        uses: actions/checkout@v4
+        uses: actions/checkout@v2
 
       - name: Set up Node.js
         uses: actions/setup-node@v4
@@ -23,27 +24,32 @@ jobs:
 
       - name: Run ESLint
         run: |
-          npm run lint 2>&1 | \
-          # generate full-lint.log
-          tee "full-lint.log"
-          # save exit code
-          exit_code="${PIPESTATUS[0]}"
-          # parsing and generate summary-lint-errors.log
-          grep -E '^\[warn\]|^Error:|^Warning:' "full-lint.log" > "summary-lint-errors.log" || \
-          echo "No lint errors found." > "summary-lint-errors.log"
-          # execute exit code
-          exit "$exit_code"
+          set -o pipefail
+          npm run lint 2>&1 | tee full-lint.log
+        continue-on-error: true
 
-      - name: Upload full-lint.log
-        uses: actions/upload-artifact@v4
-        if: success() || failure()
-        with:
-          name: lint-results
-          path: |
-            # full-lint.log
-            full-lint.log
-            # summary-lint-errors.log
-            summary-lint-errors.log
+      - name: Extract lint summary
+        run: |
+          if grep -E '^\[warn\]|^Error:|^Warning:' full-lint.log > summary-lint-errors.log; then
+          echo "Lint issues found."
+          else
+          echo "No lint errors found." > summary-lint-errors.log
+          fi
+
+          - name: Upload lint logs
+            uses: actions/upload-artifact@v4
+            with:
+              name: lint-results
+              path: |
+                full-lint.log
+                summary-lint-errors.log
+
+          - name: Fail if lint errors exist
+            run: |
+              if grep -q 'error' summary-lint-errors.log; then
+                echo "❌ ESLint errors found. See summary-lint-errors.log for details."
+                exit 1
+              fi
 
 #    strategy:
 #      matrix:
