feat: little change

diff --git a/.github/workflows/ci-pr-to-develop.yaml b/.github/workflows/ci-pr-to-develop.yaml
--- a/.github/workflows/ci-pr-to-develop.yaml
+++ b/.github/workflows/ci-pr-to-develop.yaml
@@ -34,29 +34,29 @@ jobs:
 
       - name: Run ESLint
         run: |
-          npm run lint > full-lint.log 2>&1
-          lint_exit_code=$?
-
+          npm run lint 2>&1 | tee full-lint.log
+          exit_code="${PIPESTATUS[0]}"
+          
           SUMMARY_LINT_FILE="summary-lint-errors.log"
-
-          grep_output=$(grep -E '\[warn\]|Error:|Warning:' full-lint.log)
-          grep_exit_code=$?
-
-          if [ "$grep_exit_code" -eq 0 ]; then
+          
+          grep -E '\[warn\]|Error:|Warning:' full-lint.log
+          if [ "$?" -eq 0 ]; then
             echo "$grep_output" > "$SUMMARY_LINT_FILE"
           else
             echo "✅ No lint issues found." > "$SUMMARY_LINT_FILE"
           fi
-
-          cat "$SUMMARY_LINT_FILE"
-
-          if [ "$lint_exit_code" -ne 0 ]; then
-            echo "❌ ESLint errors found."
+          
+          if [ "$exit_code" -ne 0 ]; then
+            echo ""
+            echo "❌ ESLint errors found. See $SUMMARY_LINT_FILE for details."
+            echo ""
           else
+            echo ""
             echo "✅ No lint errors."
+            echo ""
           fi
-
-          exit "$lint_exit_code"
+          
+          exit "$exit_code"
 
       - name: Upload lint logs
         uses: actions/upload-artifact@v4
