tab blin

diff --git a/.github/workflows/ci-pr-to-develop.yml b/.github/workflows/ci-pr-to-develop.yml
--- a/.github/workflows/ci-pr-to-develop.yml
+++ b/.github/workflows/ci-pr-to-develop.yml
@@ -36,20 +36,20 @@ jobs:
           echo "No lint errors found." > summary-lint-errors.log
           fi
 
-          - name: Upload lint logs
-            uses: actions/upload-artifact@v4
-            with:
-              name: lint-results
-              path: |
-                full-lint.log
-                summary-lint-errors.log
+      - name: Upload lint logs
+        uses: actions/upload-artifact@v4
+        with:
+          name: lint-results
+          path: |
+            full-lint.log
+            summary-lint-errors.log
 
-          - name: Fail if lint errors exist
-            run: |
-              if grep -q 'error' summary-lint-errors.log; then
-                echo "❌ ESLint errors found. See summary-lint-errors.log for details."
-                exit 1
-              fi
+      - name: Fail if lint errors exist
+        run: |
+          if grep -q 'error' summary-lint-errors.log; then
+            echo "❌ ESLint errors found. See summary-lint-errors.log for details."
+            exit 1
+          fi
 
 #    strategy:
 #      matrix:
