fix: maybe like that ?

diff --git a/.github/workflows/ci-pr-to-develop.yaml b/.github/workflows/ci-pr-to-develop.yaml
--- a/.github/workflows/ci-pr-to-develop.yaml
+++ b/.github/workflows/ci-pr-to-develop.yaml
@@ -34,35 +34,29 @@ jobs:
 
       - name: Run ESLint
         run: |
-          npm run lint 2>&1 | tee full-lint.log
-          exit_code=$?
-          
+          npm run lint > full-lint.log 2>&1
+          lint_exit_code=$?
+
           SUMMARY_LINT_FILE="summary-lint-errors.log"
-          
+
           grep_output=$(grep -E '\[warn\]|Error:|Warning:' full-lint.log)
-          grep_exit_code=$? # Код виходу grep
-          
+          grep_exit_code=$?
+
           if [ "$grep_exit_code" -eq 0 ]; then
             echo "$grep_output" > "$SUMMARY_LINT_FILE"
           else
             echo "✅ No lint issues found." > "$SUMMARY_LINT_FILE"
           fi
-          
-          echo "--- Content of summary-lint-errors.log (in run-lint) AFTER explicit write ---"
+
           cat "$SUMMARY_LINT_FILE"
-          echo "--- End of content ---"
-          
-          if [ "$exit_code" -ne 0 ]; then
-            echo ""
-            echo "❌ ESLint errors found. See $SUMMARY_LINT_FILE for details."
-            echo ""
+
+          if [ "$lint_exit_code" -ne 0 ]; then
+            echo "❌ ESLint errors found."
           else
-            echo ""
             echo "✅ No lint errors."
-            echo ""
           fi
-          
-          exit "$exit_code"
+
+          exit "$lint_exit_code"
 
       - name: Upload lint logs
         uses: actions/upload-artifact@v4
